services:
  nginx:
    build:
      context: ./deploy/docker/nginx
    volumes:
      #- ./logs/nginx:/var/log/nginx # Для отладки
      - ./web/static:/var/www/static:ro
      - ./${DIR_DATA}:/${DIR_DATA}:ro
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    depends_on:
      - app
    ports:
      - ${PORT_XML_PLAYER}:80
    networks:
      - default

  app:
    build:
      context: . # Контекст - папка с кодом будет в /cmd/app
      dockerfile: deploy/docker/app/Dockerfile # Путь относительно контекста
    environment:
      - EXTERNAL_PORT=${PORT_XML_PLAYER}
    #ports:
    #  - "1777:1777" # Для отладки, если нужно знать что отдаёт go приложение
    volumes:
      - ./${DIR_DATA}:/${DIR_DATA}:ro
    container_name: ${PROJECT_NAME}-app
    restart: always
    networks:
      - default

  transmission:
    build:
      context: deploy/docker/transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data:/downloads/complete
      - ./deploy/docker/transmission/transmission_config:/config
    container_name: ${PROJECT_NAME}-transmission
    ports:
      - ${PORT_TORRENT_WEB}:9091
      - "51413:51413"
      - "51413:51413/udp"
    restart: unless-stopped
    networks:
      - default
    user: "1000:1000"

networks:
  default:
    name: ${PROJECT_NAME}-network