# Название контейнера с DockerHub
FROM lscr.io/linuxserver/transmission:latest

# Рабочая директория в контейнере (используется локальная, смотри docker-compose.yml в корне проект)
#WORKDIR /home-media-app